my_project/apps/a_stripe/urls.py
from django.contrib import admin
from django.urls import path,include
# products/urls.py

from .views import (
    ProductDetailView,
    ProductListView,
    CreateStripeCheckoutSessionView,
    SuccessView,
    CancelView,
    stripe_webhook,
)

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="product-list"),
    path("<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path(
        "create-checkout-session/<int:pk>/",
        CreateStripeCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
    path("success/", SuccessView.as_view(), name="success"),
    path("cancel/", CancelView.as_view(), name="cancel"),
    path("webhook/", stripe_webhook),
]

my_project/apps/post/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
app_name = "post"

urlpatterns = [
    path('createpost/', views.create_post, name='cpost'),
    path('myposts/', views.my_posts, name='mpost'),
    # path('allposts/', views.all_posts, name="apost"),
    path('fposts/', views.friend_posts, name="fpost"),
    path('myposts/edit/<int:id>', views.edit_posts, name="epost"),
    path('myposts/dpost/<int:id>', views.del_post, name="dpost"),
    path('myposts/detpost/<int:id>', cache_page(10*60)(views.det_post), name="detpost"),
    path('lpost/<int:id>', views.like_post, name="lpost"),
    path('comments/<int:id>', views.comment_post, name="comment"),
    path('fcomments/<int:id>', views.fetch_comments, name="fcomments"),
    path('freplies/<int:id>', views.fetch_replies, name="fr"),
    path('cedit/<int:id>', views.edit_comment, name="ec"),
    path('cdelete/<int:id>', views.delete_comment, name="dc"),
    # path('checkout/<int:post_id>', views.CheckoutView.as_view(), name="checkout"),
    path('create-payment/<int:post_id>', views.CreatePaymentView.as_view(), name="create_payment"),
    # path('success/', views.success, name="success"),
    # path('cancel', views.cancel, name="cancel"),
]

my_project/apps/user/urls.py
from django.urls import path, include
from user import views
from rest_framework.routers import DefaultRouter
# from .views import UserViewSet

router = DefaultRouter()

# router.register('userhapi/', UserViewSet, basename='users')
app_name = "user"

urlpatterns = [
    path('', views.login, name='login-page'),
    path('register/', views.register, name='register'),
    path('fpass/', views.fpassword, name='forgotpass'),
    path('rpass/<int:id>', views.rpassword, name='respass'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    # path('mypost/', views.mypost, name='mypost'),
    path('allposts/', views.all_posts, name='apost'),
    # path('userhapi/', include(router.urls)),
    path('vcode/<int:id>', views.vcode, name='vcode'),
    path('rcode/<int:id>', views.rcode, name='rcode'),
    path('resetpass/<int:id>', views.resetpass, name='resetpass'),

]

my_project/urls.py
from django.contrib import admin
from django.urls import path ,include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import serializers, viewsets, routers
from user.models import CustomUser
from testing import views
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.views.static import serve
# from user.models import User

# Serializer define the API representation
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ['url', 'username', 'email', 'is_staff']

# # Viewset define the behaviour of Views
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer


# Router are used for automatic routing


# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

def trigger_error(request):
    division_by_zero = 1 / 0


if settings.DEBUG:
    urlpatterns = [
        # path('', include(router.urls)),
        path('admin/', admin.site.urls),
        path('', include('user.urls')),
        path('post/', include('post.urls')),
        path('products/', include('a_stripe.urls'), name="products"),
        # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
        # path('postapi/', include('post.api_urls.urls')),
        # path('userapi/', include('user.api_urls.urls')),
        path('sentry-debug/', trigger_error),
        path('api/', include('api_urls.urls')),
        path('sauth/', include('social_django.urls', namespace='social')),
        # path('testing/', cache_page(30)(views.testHome)),
        # path('testing/home/', views.testHome),
        # path('testing/contact/', views.contact),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

else:
    urlpatterns = [
        # path('', include(router.urls)),
        path('admin/', admin.site.urls),
        path('', include('user.urls')),
        path('post/', include('post.urls')),
        path('products/', include('a_stripe.urls'), name="products"),
        # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
        # path('postapi/', include('post.api_urls.urls')),
        # path('userapi/', include('user.api_urls.urls')),
        path('sentry-debug/', trigger_error),
        path('api/', include('api_urls.urls')),
        path('sauth/', include('social_django.urls', namespace='social')),
        # path('testing/', cache_page(30)(views.testHome)),
        # path('testing/home/', views.testHome),
        # path('testing/contact/', views.contact),
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

my_project/apps/a_stripe/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _
CustomUser = get_user_model()
# Create your models here.


# products/models.py


User = settings.AUTH_USER_MODEL

def get_image_filename(instance, filename):
    name = instance.name
    slug = slugify(name)
    return f"products/{slug}-{filename}"

class ProductTag(models.Model):
    name = models.CharField(
        max_length=100, help_text=_("Designates the name of the tag.")
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    tags = models.ManyToManyField(ProductTag, blank=True)
    desc = models.TextField(_("Description"), blank=True)
    thumbnail = models.ImageField(upload_to=get_image_filename, blank=True)
    url = models.URLField()
    quantity = models.IntegerField(default=1)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return self.name

class Price(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(decimal_places=2, max_digits=10)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.product.name} {self.price}"


class PurchaseHistory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    purchase_success = models.BooleanField(default=False)
    user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)
    amount_paid = models.CharField(max_length=50, default=0)
    created_at = models.DateTimeField(auto_now_add=True)



# class UserPayment(models.Model):
#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
#     stripe_customer_id = models.CharField(max_length=255)
#     stripe_checkout_id = models.CharField(max_length=255)
#     stripe_product_id = models.CharField(max_length=255)
#     product_name = models.CharField(max_length=255)
#     quantity = models.IntegerField(default=1)
#     price = models.DecimalField(max_digits=10, decimal_places=2)
#     currency = models.CharField(max_length=3)
#     has_paid = models.BooleanField(default=False)


#     def __str__(self):
#         return f"{self.user.username} - {self.product_name} - Paid: {self.has_paid}"
    

my_project/apps/post/forms.py
from django import forms
from .models import PostModel, PostComments

class PostForm(forms.Form):
    title = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)
    content = forms.ImageField()

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = PostModel
        fields = ['post_title', 'post_description', 'post_content']


class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComments
        fields = ['comment_desc']

class ReplyForm(forms.ModelForm):
    class Meta:
        model = PostComments
        # fields = ['comment_desc', 'com_user', 'com_reply', 'reply_on_comment']
        fields = ['comment_desc', 'reply_on_comment']

my_project/apps/user/forms.py
from django import forms
from .models import CustomUser
# from django.contrib.auth.models import User
# from django.contrib.auth.models import CustomUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from rest_framework import serializers
import re
from django.core.exceptions import ValidationError
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    #  Configuration
    class Meta():
        model = CustomUser
        # fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'contact']
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'contact', 'dob']
        widgets = {
            # 'dob': forms.extras.SelectDateWidget
            'dob': forms.SelectDateWidget(years=range(1980, 2015))
        }


class UserCreationForm(serializers.Serializer):
    # username = serializers.CharField(max_length=50, required=True)
    email = serializers.EmailField(required=True)
    is_staff = serializers.BooleanField(required=False, default=False)



# def validate_password(value):
#     # if re.search()
#     breakpoint()
#     if not bool(re.search(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$", value)):
#         raise ValidationError("Password must contain Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character.")
#     return value

class ResetPassword(forms.Form):
    password = forms.CharField(max_length=30)
    # password = forms.CharField(max_length=30, validators=[validate_password])

    def clean_password(self):
        # if re.search()
        # breakpoint()
        if not bool(re.search(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$", self.cleaned_data['password'])):
            raise ValidationError("Password must contain Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character.")
        return self.cleaned_data['password']

my_project/apps/a_stripe/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import DetailView, ListView

from .models import Price, Product
from user.models import CustomUser, Stars
import stripe
from django.conf import settings
from django.shortcuts import redirect
from .models import Price, Product, PurchaseHistory
from django.views.generic import TemplateView
import json
from django.http.response import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.
# products/views.py


class ProductListView(ListView):
    model = Product
    context_object_name = "products"
    template_name = "a_stripe/product_list.html"

class ProductDetailView(DetailView):
    model = Product
    context_object_name = "product"
    template_name = "a_stripe/product_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data()
        context["prices"] = Price.objects.filter(product=self.get_object())
        return context
    


class CreateStripeCheckoutSessionView(View):
    """
    Create a checkout session and redirect the user to Stripe's checkout page
    """

    def post(self, request, *args, **kwargs):
        price = Price.objects.get(id=self.kwargs["pk"])

        # breakpoint()
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=["card"],
            line_items=[
                {
                    "price_data": {
                        "currency": "usd",
                        "unit_amount": int(price.price) * 100,
                        "product_data": {
                            "name": price.product.name,
                            "description": price.product.desc,
                            "images": [
                                f"{settings.BACKEND_DOMAIN}{price.product.thumbnail.url}"
                            ],
                        },
                    },
                    "quantity": price.product.quantity,
                }
            ],
            metadata={
                "product_id": price.product.id,
                "user_id": request.user.id,
                "quantity": price.product.quantity,
                "amount_paid": int(price.price) * price.product.quantity,
            },
            mode="payment",
            success_url=settings.PAYMENT_SUCCESS_URL,
            cancel_url=settings.PAYMENT_CANCEL_URL,
        )
        return redirect(checkout_session.url)
    


class SuccessView(TemplateView):
    template_name = "a_stripe/success.html"

    def get(self, request, *args, **kwargs):
        print("get", request.body)
        # breakpoint()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # breakpoint()
        print("post", request.body)
        return super().post(request, *args, **kwargs)
    


class CancelView(TemplateView):
    template_name = "a_stripe/cancel.html"


# payments/views.py

@csrf_exempt
def stripe_webhook(request):
# payment views
    stripe.api_key = settings.STRIPE_SECRET_KEY
    endpoint_secret = settings.STRIPE_ENDPOINT_SECRET
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    # except ValueError as e:
    except ValueError:
        # Invalid payload
        # print(e)
        return HttpResponse(status=400)
    
    # except stripe.error.SignatureVerificationError as e:
    except stripe.error.SignatureVerificationError:
        # Invalid signature
        # print(e)
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        print("Payment was successful.")
        session = event['data']['object']
        # breakpoint()
        product_id = session['metadata']['product_id']
        user_id = session['metadata']['user_id']
        quantity = int(session['metadata']['quantity'])
        amount_paid = session['metadata']['amount_paid']
        get_product = Product.objects.get(id=product_id)
        get_user = CustomUser.objects.get(id=user_id)
        print("amount paid", amount_paid)
        PurchaseHistory.objects.create(product=get_product, purchase_success=True, user=get_user, amount_paid=amount_paid)
        stars = Stars.objects.get(user_id=user_id)
        stars.amount += quantity
        stars.save()
        # TODO:
        # breakpoint()
        # import json
        # obj = request.body.decode('utf-8')
        # obj = json.loads(obj)
        # print(obj['data']['object']['metadata']['product_id'])


    return HttpResponse(status=200)


# # Using Django
# @csrf_exempt
# def my_webhook_view(request):
#     payload = request.body
#     event = None

#     try:
#         event = stripe.Event.construct_from(
#             json.loads(payload), stripe.api_key
#         )
#     except ValueError as e:
#     # Invalid payload
#         return HttpResponse(status=400)

#     # Handle the event
#     if event.type == 'payment_intent.succeeded':
#         payment_intent = event.data.object # contains a stripe.PaymentIntent
#         # Then define and call a method to handle the successful payment intent.
#         # handle_payment_intent_succeeded(payment_intent)
#     elif event.type == 'payment_method.attached':
#         payment_method = event.data.object # contains a stripe.PaymentMethod
#         # Then define and call a method to handle the successful attachment of a PaymentMethod.
#         # handle_payment_method_attached(payment_method)
#         # ... handle other event types
#     else:
#         print('Unhandled event type {}'.format(event.type))

#     return HttpResponse(status=200)

my_project/apps/myapp/views.py
from django.shortcuts import render

# Create your views here.

my_project/apps/testing/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_page, never_cache
# Create your views here.


# @cache_page(30)
def testHome(request):
    #  function to test caching
    return render(request, "testing/testhome.html")


# @never_cache
def contact(request):
    #  function to test caching
    return render(request, "testing/contact.html")

my_project/templates/user/api_register.html
{% load rest_framework %}
<html>
    <body>
        <form action="{% url 'create_apiuser' %}" method='POST'>
            {% csrf_token %}
            {% render_form serializer %}
            <input type="submit" value="Save">
        </form>
    </body>
</html>

my_project/templates/user/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'user/css/styles.css' %}">
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <div id="pform">
            <div id="l1">
                <a href="{% url 'post:mpost' %}" class="btn">My Posts</a>
            </div>
            {% comment %} <div id="l2">
                <a href="{% url 'post:fpost' %}" class="btn">Friends Posts</a>
            </div> {% endcomment %}
            <div id="l3">
                <a href="{% url 'post:apost' %}" class="btn">All Posts</a>
            </div>
            <div id="l4">
                <a href="{% url 'post:cpost' %}" class="btn">Create a Post</a>
            </div>
    </div>
    <div style="border: 1px solid blue; width: 10%;background: blue;color: white;font-size: 30px;position: absolute;left: 80%;top: 5%;text-align:center;">
        {{ user.username }}
        <form action="{% url 'user:logout' %}" method="post">                        
            {% csrf_token %}
            <button id="lbtn" type="submit">Log Out</button>
        </form>
    </div>
{% else%}
    <div style="background:red; color: white; text-align: center;"><h1>You are not Logged In !!!</h1></div>
    <a href="{% url 'user:login-page' %}">Login</a>
{% endif %}
{% endblock %}

my_project/templates/user/ecode.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'user/css/styles.css' %}">
{% endblock %}
{% block content %}
<div class="f_header mt-2">
    <div class="float-left">
        <svg height="40px" xmlns="http://www.w3.org/2000/svg">
            <image height="40" href="{% static 'user/images/fbimg.svg' %}" />
        </svg>
    </div>
</div>
<div style="background-color: #e8eaee; margin-top: 5px; padding-top: 30px; padding-bottom: 30px;">
    <div class="card w-50 mx-auto mt-2">
      <div class="card-header">
        Enter security code
      </div>
      <div class="card-body">
        <div>
            {% if error %}
            <div style="background:#feeae8; color: white; border: 1px solid #f3aa9e;color:black; font-size:20px;" id="emsg">{{error}}</div>
            {% endif %}
        </div>
        <h5 class="card-title">Please check your phone for an email message with your code. Your code is 8 characters in length.</h5>
        <form method="post" action="{% url 'user:vcode' id%}">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="rcode" class="form-control w-50" placeholder="Enter Code">
            </div>
      </div>
      <div class="card-footer">
        <div class="float-left w-25">
            <a href="{% url 'user:login-page' %}">Didn't get a code?</a>
        </div>
        <div class="float-right w-75">
            <a href="{% url 'user:login-page' %}" class="btn" style="background-color: #e5e7eb; color:black;">Cancel</a>
            <input class="btn btn-primary" type="submit" name="submit" value="submit">
        </div>
        </form>
      </div>
    </div>
</div>
{% endblock %}

{% block javas %}
<script src="{% static 'post/js/script.js' %}"></script>
<script src="{% static 'user/js/script.js' %}"></script>
{% endblock %}

my_project/templates/user/fpass.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'user/css/styles.css' %}">
{% endblock %}
{% block content %}
<div class="f_header mt-2">
    <div class="float-left">
        <svg height="40px" xmlns="http://www.w3.org/2000/svg">
            <image height="40" href="{% static 'user/images/fbimg.svg' %}" />
        </svg>
    </div>
    <div class="float-right">
        <form method="post" class="form-inline">
            {% csrf_token %}
            <div class="form-group ml-1">
            <input type="text" class="form-control" name="username" autocapitalize="none" autocomplete="username" maxlength="254" required="" id="id_username">
        </div>
        <div class="form-group ml-1">
            <input type="password" class="form-control" name="password" autocomplete="current-password" required="" id="id_password">
        </div>
        <div class="form-group ml-1">
            <button class="btn btn-primary" type="submit">Log In</button>
        </div>
            <a id="fp" href="{% url 'user:forgotpass' %}"> Forgotten Password? </a>
        </form>
    </div>
</div>
<div style="background-color: #e8eaee; margin-top: 5px; padding-top: 30px; padding-bottom: 30px;">
    <div class="card w-50 mx-auto mt-2">
      <div class="card-header">
        Find Your Account
      </div>
      <div class="card-body">
        <div>
            {% if error %}
            <div style="background:#feeae8; color: white; border: 1px solid #f3aa9e;color:black; font-size:20px;" id="emsg">{{error}}</div>
            {% endif %}
        </div>
        <h5 class="card-title">Please enter your email address or mobile number to search for your account.</h5>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="email" class="form-control w-75" placeholder="Email address or mobile number">
            </div>
      </div>
      <div class="card-footer"  style="text-align:right">
            <a href="{% url 'user:login-page' %}" class="btn" style="background-color: #e5e7eb; color:black;">Cancel</a>
            <input class="btn btn-primary" type="submit" name="submit" value="search">
        </form>
      </div>
    </div>
</div>
{% endblock %}

{% block javas %}
<script src="{% static 'post/js/script.js' %}"></script>
<script src="{% static 'user/js/script.js' %}"></script>
{% endblock %}

my_project/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'user/css/styles.css' %}">
{% endblock %}
{% block content %}
<div id="limg">
    <img src="{% static 'user/images/fbimg.svg' %}">
    <p id="lp">Facebook helps you connect and<br>share with the people in your life.</p
</div>
<div id="lform">
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <br>
        <div class="form-group">
        <button class="btn btn-primary btn-lg btn-block" id="libtn" type="submit">Log In</button>
        </div>
        <br>
        <a id="fp" href="{% url 'user:forgotpass' %}"> Forgotten Password</a>
    </form>
    <hr>
    <!-- Sign Up form -->
    <div class="">
        <a  class="btn btn-success btn-lg btn-block" id="sbtn" href="{% url 'user:register' %}">Create new account</a>
    </div>
    <!-- Social Accounts --> 
    <div id="social_acc">
        <br>
        <a class="btn btn-block btn-social btn-google text-center" href="{% url 'social:begin' 'google-oauth2' %}">
            <img src="{% static 'user/images/branding_guideline_sample_lt_sq_sl.svg' %}" alt="my image"/>Sign in with Google
        </a>
        <p class="text-center"><strong>-- OR --</strong></p>
            <a class="btn btn-block btn-social btn-facebook text-center" href="{% url 'social:begin' 'facebook' %}">
                Login with Facebook<img src="{% static 'user/images/Facebook_Logo_Primary.png' %}"/>
            </a>
        <p class="text-center"><strong>-- OR --</strong></p>
            <a class="btn btn-block btn-social btn-github text-center" href="{% url 'social:begin' 'github' %}">
                Login with GitHub<img src="{% static 'user/images/github-mark-white.svg' %}"/>
            </a>
    </div>
</div>
{% endblock %}

{% block javas %}
<script src="{% static 'post/js/script.js' %}"></script>
<script src="{% static 'user/js/script.js' %}"></script>
{% endblock %}

my_project/templates/user/rpass.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'user/css/styles.css' %}">
{% endblock %}
{% block content %}
<div class="f_header mt-2">
    <div class="float-left">
        <svg height="40px" xmlns="http://www.w3.org/2000/svg">
            <image height="40" href="{% static 'user/images/fbimg.svg' %}" />
        </svg>
    </div>
    <div class="float-right">
        <form method="post" class="form-inline">
            {% csrf_token %}
            <div class="form-group ml-1">
            <input type="text" class="form-control" name="username" autocapitalize="none" autocomplete="username" maxlength="254" required="" id="id_username">
        </div>
        <div class="form-group ml-1">
            <input type="password" class="form-control" name="password" autocomplete="current-password" required="" id="id_password">
        </div>
        <div class="form-group ml-1">
            <button class="btn btn-primary" type="submit">Log In</button>
        </div>
            <a id="fp" href="{% url 'user:forgotpass' %}"> Forgotten Password? </a>
        </form>
    </div>
</div>
<div style="background-color: #e8eaee; margin-top: 5px; padding-top: 30px; padding-bottom: 30px;">
    <div class="card w-50 mx-auto mt-2">
      <div class="card-header">
        Reset Your Password
      </div>
      <div class="card-body">
        <div id="b1" class="float-left w-50">
            <h5 class="card-title">How do you want to receive the code to reset your password?</h5>
            <form method="post" action="{% url 'user:rcode' id %}">
                {% csrf_token %}
            <div class="form-check">
              <input class="form-check-input" type="radio" name="ropt" value="1" id="opt1">
              <label class="form-check-label" for="opt1">
                Send code via Facebook notification<br>
                <span style="font-size:15px; line-height:0.2;">You're logged in on another app<br> or device. Get a notification with a login<br> code.</span>
              </label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="ropt" id="opt2" value="2" checked>
              <label class="form-check-label" for="opt2">
                Send code via SMS<br>
                <span style="font-size:15px;">{{value}}</span>
              </label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="ropt" id="opt3" value="3">
              <label class="form-check-label" for="opt3">
                Enter Password to Log In
              </label>
            </div>
        </div>
        <div id="b2" class="float-right w-25 pt-1" style="border:1px solid red; height:150px;text-align:center;">
            <svg xmlns="http://www.w3.org/2000/svg" height="90" width="108" viewBox="0 0 448 512">
                <circle r="310" cx="225" cy="300" fill="#d3d7db" />
                <!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M304 128a80 80 0 1 0 -160 0 80 80 0 1 0 160 0zM96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM49.3 464l349.5 0c-8.9-63.3-63.3-112-129-112l-91.4 0c-65.7 0-120.1 48.7-129 112zM0 482.3C0 383.8 79.8 304 178.3 304l91.4 0C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7L29.7 512C13.3 512 0 498.7 0 482.3z"/>
                <span style="text-align:center;">{{value}}<br>
                Facebook User</span>
            </svg>
            <!-- <i class="fa-regular fa-user"></i> -->
        </div>
      </div>
      <div class="card-footer"  style="text-align:right">
            <a href="{% url 'user:login-page' %}" class="btn" style="background-color: #e5e7eb; color:black;">Cancel</a>
            <input class="btn btn-primary" type="submit" name="submit" value="search">
        </form>
      </div>
    </div>
</div>
{% endblock %}

{% block javas %}
<script src="{% static 'post/js/script.js' %}"></script>
<script src="{% static 'user/js/script.js' %}"></script>
{% endblock %}