my_project/apps/a_stripe/urls.py
from django.contrib import admin
from django.urls import path,include
# products/urls.py

from .views import (
    ProductDetailView,
    ProductListView,
    CreateStripeCheckoutSessionView,
    SuccessView,
    CancelView,
    stripe_webhook,
)

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="product-list"),
    path("<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path(
        "create-checkout-session/<int:pk>/",
        CreateStripeCheckoutSessionView.as_view(),
        name="create-checkout-session",
    ),
    path("success/", SuccessView.as_view(), name="success"),
    path("cancel/", CancelView.as_view(), name="cancel"),
    path("webhook/", stripe_webhook),
]

my_project/apps/post/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page
app_name = "post"

urlpatterns = [
    path('createpost/', views.create_post, name='cpost'),
    path('myposts/', views.my_posts, name='mpost'),
    # path('allposts/', views.all_posts, name="apost"),
    path('fposts/', views.friend_posts, name="fpost"),
    path('myposts/edit/<int:id>', views.edit_posts, name="epost"),
    path('myposts/dpost/<int:id>', views.del_post, name="dpost"),
    path('myposts/detpost/<int:id>', cache_page(10*60)(views.det_post), name="detpost"),
    path('lpost/<int:id>', views.like_post, name="lpost"),
    path('comments/<int:id>', views.comment_post, name="comment"),
    path('fcomments/<int:id>', views.fetch_comments, name="fcomments"),
    path('freplies/<int:id>', views.fetch_replies, name="fr"),
    path('cedit/<int:id>', views.edit_comment, name="ec"),
    path('cdelete/<int:id>', views.delete_comment, name="dc"),
    # path('checkout/<int:post_id>', views.CheckoutView.as_view(), name="checkout"),
    path('create-payment/<int:post_id>', views.CreatePaymentView.as_view(), name="create_payment"),
    # path('success/', views.success, name="success"),
    # path('cancel', views.cancel, name="cancel"),
]

my_project/apps/user/urls.py
from django.urls import path, include
from user import views
from rest_framework.routers import DefaultRouter
# from .views import UserViewSet

router = DefaultRouter()

# router.register('userhapi/', UserViewSet, basename='users')
app_name = "user"

urlpatterns = [
    path('', views.login, name='login-page'),
    path('register/', views.register, name='register'),
    path('fpass/', views.fpassword, name='forgotpass'),
    path('rpass/<int:id>', views.rpassword, name='respass'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout, name='logout'),
    # path('mypost/', views.mypost, name='mypost'),
    path('allposts/', views.all_posts, name='apost'),
    # path('userhapi/', include(router.urls)),
    path('vcode/<int:id>', views.vcode, name='vcode'),
    path('rcode/<int:id>', views.rcode, name='rcode'),
    path('resetpass/<int:id>', views.resetpass, name='resetpass'),

]

my_project/urls.py
from django.contrib import admin
from django.urls import path ,include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import serializers, viewsets, routers
from user.models import CustomUser
from testing import views
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.views.static import serve
# from user.models import User

# Serializer define the API representation
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ['url', 'username', 'email', 'is_staff']

# # Viewset define the behaviour of Views
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer


# Router are used for automatic routing


# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

def trigger_error(request):
    division_by_zero = 1 / 0


if settings.DEBUG:
    urlpatterns = [
        # path('', include(router.urls)),
        path('admin/', admin.site.urls),
        path('', include('user.urls')),
        path('post/', include('post.urls')),
        path('products/', include('a_stripe.urls'), name="products"),
        # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
        # path('postapi/', include('post.api_urls.urls')),
        # path('userapi/', include('user.api_urls.urls')),
        path('sentry-debug/', trigger_error),
        path('api/', include('api_urls.urls')),
        path('sauth/', include('social_django.urls', namespace='social')),
        # path('testing/', cache_page(30)(views.testHome)),
        # path('testing/home/', views.testHome),
        # path('testing/contact/', views.contact),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

else:
    urlpatterns = [
        # path('', include(router.urls)),
        path('admin/', admin.site.urls),
        path('', include('user.urls')),
        path('post/', include('post.urls')),
        path('products/', include('a_stripe.urls'), name="products"),
        # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
        # path('postapi/', include('post.api_urls.urls')),
        # path('userapi/', include('user.api_urls.urls')),
        path('sentry-debug/', trigger_error),
        path('api/', include('api_urls.urls')),
        path('sauth/', include('social_django.urls', namespace='social')),
        # path('testing/', cache_page(30)(views.testHome)),
        # path('testing/home/', views.testHome),
        # path('testing/contact/', views.contact),
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

my_project/apps/a_stripe/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _
CustomUser = get_user_model()
# Create your models here.


# products/models.py


User = settings.AUTH_USER_MODEL

def get_image_filename(instance, filename):
    name = instance.name
    slug = slugify(name)
    return f"products/{slug}-{filename}"

class ProductTag(models.Model):
    name = models.CharField(
        max_length=100, help_text=_("Designates the name of the tag.")
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    tags = models.ManyToManyField(ProductTag, blank=True)
    desc = models.TextField(_("Description"), blank=True)
    thumbnail = models.ImageField(upload_to=get_image_filename, blank=True)
    url = models.URLField()
    quantity = models.IntegerField(default=1)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return self.name

class Price(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(decimal_places=2, max_digits=10)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.product.name} {self.price}"


class PurchaseHistory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    purchase_success = models.BooleanField(default=False)
    user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)
    amount_paid = models.CharField(max_length=50, default=0)
    created_at = models.DateTimeField(auto_now_add=True)



# class UserPayment(models.Model):
#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
#     stripe_customer_id = models.CharField(max_length=255)
#     stripe_checkout_id = models.CharField(max_length=255)
#     stripe_product_id = models.CharField(max_length=255)
#     product_name = models.CharField(max_length=255)
#     quantity = models.IntegerField(default=1)
#     price = models.DecimalField(max_digits=10, decimal_places=2)
#     currency = models.CharField(max_length=3)
#     has_paid = models.BooleanField(default=False)


#     def __str__(self):
#         return f"{self.user.username} - {self.product_name} - Paid: {self.has_paid}"
    

my_project/apps/post/forms.py
from django import forms
from .models import PostModel, PostComments

class PostForm(forms.Form):
    title = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)
    content = forms.ImageField()

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = PostModel
        fields = ['post_title', 'post_description', 'post_content']


class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComments
        fields = ['comment_desc']

class ReplyForm(forms.ModelForm):
    class Meta:
        model = PostComments
        # fields = ['comment_desc', 'com_user', 'com_reply', 'reply_on_comment']
        fields = ['comment_desc', 'reply_on_comment']

my_project/apps/user/forms.py
from django import forms
from .models import CustomUser
# from django.contrib.auth.models import User
# from django.contrib.auth.models import CustomUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from rest_framework import serializers
import re
from django.core.exceptions import ValidationError
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    #  Configuration
    class Meta():
        model = CustomUser
        # fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'contact']
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'contact', 'dob']
        widgets = {
            # 'dob': forms.extras.SelectDateWidget
            'dob': forms.SelectDateWidget(years=range(1980, 2015))
        }


class UserCreationForm(serializers.Serializer):
    # username = serializers.CharField(max_length=50, required=True)
    email = serializers.EmailField(required=True)
    is_staff = serializers.BooleanField(required=False, default=False)



# def validate_password(value):
#     # if re.search()
#     breakpoint()
#     if not bool(re.search(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$", value)):
#         raise ValidationError("Password must contain Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character.")
#     return value

class ResetPassword(forms.Form):
    password = forms.CharField(max_length=30)
    # password = forms.CharField(max_length=30, validators=[validate_password])

    def clean_password(self):
        # if re.search()
        # breakpoint()
        if not bool(re.search(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$", self.cleaned_data['password'])):
            raise ValidationError("Password must contain Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character.")
        return self.cleaned_data['password']

my_project/apps/a_stripe/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import DetailView, ListView

from .models import Price, Product
from user.models import CustomUser, Stars
import stripe
from django.conf import settings
from django.shortcuts import redirect
from .models import Price, Product, PurchaseHistory
from django.views.generic import TemplateView
import json
from django.http.response import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.
# products/views.py


class ProductListView(ListView):
    model = Product
    context_object_name = "products"
    template_name = "a_stripe/product_list.html"

class ProductDetailView(DetailView):
    model = Product
    context_object_name = "product"
    template_name = "a_stripe/product_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data()
        context["prices"] = Price.objects.filter(product=self.get_object())
        return context
    


class CreateStripeCheckoutSessionView(View):
    """
    Create a checkout session and redirect the user to Stripe's checkout page
    """

    def post(self, request, *args, **kwargs):
        price = Price.objects.get(id=self.kwargs["pk"])

        # breakpoint()
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=["card"],
            line_items=[
                {
                    "price_data": {
                        "currency": "usd",
                        "unit_amount": int(price.price) * 100,
                        "product_data": {
                            "name": price.product.name,
                            "description": price.product.desc,
                            "images": [
                                f"{settings.BACKEND_DOMAIN}{price.product.thumbnail.url}"
                            ],
                        },
                    },
                    "quantity": price.product.quantity,
                }
            ],
            metadata={
                "product_id": price.product.id,
                "user_id": request.user.id,
                "quantity": price.product.quantity,
                "amount_paid": int(price.price) * price.product.quantity,
            },
            mode="payment",
            success_url=settings.PAYMENT_SUCCESS_URL,
            cancel_url=settings.PAYMENT_CANCEL_URL,
        )
        return redirect(checkout_session.url)
    


class SuccessView(TemplateView):
    template_name = "a_stripe/success.html"

    def get(self, request, *args, **kwargs):
        print("get", request.body)
        # breakpoint()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # breakpoint()
        print("post", request.body)
        return super().post(request, *args, **kwargs)
    


class CancelView(TemplateView):
    template_name = "a_stripe/cancel.html"


# payments/views.py

@csrf_exempt
def stripe_webhook(request):
# payment views
    stripe.api_key = settings.STRIPE_SECRET_KEY
    endpoint_secret = settings.STRIPE_ENDPOINT_SECRET
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    # except ValueError as e:
    except ValueError:
        # Invalid payload
        # print(e)
        return HttpResponse(status=400)
    
    # except stripe.error.SignatureVerificationError as e:
    except stripe.error.SignatureVerificationError:
        # Invalid signature
        # print(e)
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        print("Payment was successful.")
        session = event['data']['object']
        # breakpoint()
        product_id = session['metadata']['product_id']
        user_id = session['metadata']['user_id']
        quantity = int(session['metadata']['quantity'])
        amount_paid = session['metadata']['amount_paid']
        get_product = Product.objects.get(id=product_id)
        get_user = CustomUser.objects.get(id=user_id)
        print("amount paid", amount_paid)
        PurchaseHistory.objects.create(product=get_product, purchase_success=True, user=get_user, amount_paid=amount_paid)
        stars = Stars.objects.get(user_id=user_id)
        stars.amount += quantity
        stars.save()
        # TODO:
        # breakpoint()
        # import json
        # obj = request.body.decode('utf-8')
        # obj = json.loads(obj)
        # print(obj['data']['object']['metadata']['product_id'])


    return HttpResponse(status=200)


# # Using Django
# @csrf_exempt
# def my_webhook_view(request):
#     payload = request.body
#     event = None

#     try:
#         event = stripe.Event.construct_from(
#             json.loads(payload), stripe.api_key
#         )
#     except ValueError as e:
#     # Invalid payload
#         return HttpResponse(status=400)

#     # Handle the event
#     if event.type == 'payment_intent.succeeded':
#         payment_intent = event.data.object # contains a stripe.PaymentIntent
#         # Then define and call a method to handle the successful payment intent.
#         # handle_payment_intent_succeeded(payment_intent)
#     elif event.type == 'payment_method.attached':
#         payment_method = event.data.object # contains a stripe.PaymentMethod
#         # Then define and call a method to handle the successful attachment of a PaymentMethod.
#         # handle_payment_method_attached(payment_method)
#         # ... handle other event types
#     else:
#         print('Unhandled event type {}'.format(event.type))

#     return HttpResponse(status=200)

my_project/apps/myapp/views.py
from django.shortcuts import render

# Create your views here.

my_project/apps/testing/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_page, never_cache
# Create your views here.


# @cache_page(30)
def testHome(request):
    #  function to test caching
    return render(request, "testing/testhome.html")


# @never_cache
def contact(request):
    #  function to test caching
    return render(request, "testing/contact.html")

my_project/templates/post/checkout.html
<h1>Checkout Page</h1>

my_project/templates/post/delpost.html
{% extends base.html %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}
<link rel="stylesheet" href="{% static 'post/css/styles.css' %}"/>
{% endblock %}
{% block content %}

{% endblock %}

my_project/templates/post/editpost.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'post/css/styles.css' %}"/>
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
{% if messages %}
    {% for message in messages%}
        {{message}}
    {% endfor %}
{% endif %}
<h1 class="text-primary text-center">Update Post</h1>
<div class="col-6 mt-4">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success text-center" value="submit">
</form>
</div>
<div style="border: 1px solid blue; width: 10%;background: blue;color: white;font-size: 30px;position: absolute;left: 80%;top: 5%;text-align:center;">
    {{ user.username }}
    <form action="{% url 'user:logout' %}" method="post">                        
        {% csrf_token %}
        <button id="lbtn" type="submit">Log Out</button>
    </form>
</div>
{% else %}
    <div style="background:red; color: white; text-align: center;"><h1>You are not Logged In !!!</h1></div>
    <a href="{% url 'user:login-page' %}">Login</a>
{% endif %}
{% endblock %}

my_project/templates/post/friends_post.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'post/css/styles.css' %}"/>
<link rel="stylesheet" href="{% static 'user/css/styles.css' %}"/>
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'user:apost' %}"><i class="fa-solid fa-house"></i> Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'post:fpost' %}"><i class="fas fa-users"></i> Friends Posts</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'post:mpost' %}"><i class="fa-solid fa-user"></i> My Post</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'post:cpost' %}"><i class="fa-solid fa-plus"></i> Create Post</a>
      </li>
  </ul>
  {{ user.username|json_script:"c_user"}}
    {% for post in posts %}
    <div id="fposts" class="f{{post.id}}">
        <span id="dpost">{{ post.post_date }}</span><br>
        <span id="ptitle">{{ post.post_title }}</span><br>
        <img src="{{ post.post_content.url }}" height="300"/>
        Posted By: <span id="fbuser">{{ post.post_user }}</span><br>
        {% comment %} Description: <span id="desc">{{ post.post_title }}</span><br> {% endcomment %}
        Description: <span id="dpost" class="mydesc">{{ post.post_description }}</span><span id="rbtn"><a href="{% url 'post:detpost' id=post.id %}">Read More</a></span><br>
        <span><i class="fa-solid fa-heart"></i></span> <span id="nlikes">{{post.post_likes}}</span>
        <span style="color:#FFBF00;"><i class="fas fa-star"></i></span> <span style="color:#FFBF00;" id="nstars">{{post.post_stars}}</span>
        <hr>
        <div id="popt">
          {% if post.id in likes %}
            <button class="blike liked" onclick="ldlike({{post.id}}, {{user.id}}, this)"><i class="fa-solid fa-heart"></i> Like</button>
          {% else %}
            <button class="blike" onclick="ldlike({{post.id}}, {{user.id}}, this)"><i class="fa-regular fa-heart"></i> Like</button>
          {% endif %}
          <button class="bstars" data-toggle="modal" data-target="#PaymentModal" onclick=""><i class="far fa-star"></i> Stars</button>
          <button class="bcom" data-toggle="modal" data-target="#CommentModal"><i class="fa-regular fa-comment"></i> Comment</button>
          <button class="bshare"><i class="fa-solid fa-share"></i> Share</button>
        </div>
        <div id="purl">
          {% if post.id in likes %}
            <p id="lstatus">Liked</p>
          {% else %}
            <p id="lstatus">Not Liked</p>
          {% endif %}
          {% csrf_token %}
          <p id="eurl">{% url 'post:epost' id=post.id %}</p>
          <p id="durl">{% url 'post:dpost' id=post.id %}</p>
          <p id="curl">{% url 'post:comment' id=post.id %}</p>
          <p id="fcurl">{% url 'post:fcomments' id=post.id %}</p>
        </div>
    </div><br>
    {% endfor %}

    <nav aria-label="...">
      <ul class="pagination">
        {% if posts.has_previous %}
        <li class="page-item">
          <a class="page-link" href="/post/fposts/?page=1" tabindex="-1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="/post/fposts/?page={{posts.previous_page_number}}" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% for n in totalPageList %}
        <li class="page-item">
          <a class="page-link" href="/post/fposts/?page={{n}}">{{n}}</a>
        </li>
        {% endfor %}
        {% if posts.has_next %}
        <li class="page-item">
          <a class="page-link" href="/post/fposts/?page={{posts.next_page_number}}">Next</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="/post/fposts/?page={{lastpage}}">Last</a>
        </li>
        {% endif %}
      </ul>
    </nav>

    <div class="modal fade" id="CommentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-scrollable modal-lg" role="document">
        <div class="modal-content com_modal">
          <div class="modal-header text-center">
            <h5 class="modal-title w-100" id="comptitle">Modal title</h5>
            <button type="button" class="close" id="cclose" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p id="p_user"></p>
            <div class="modal_imgbox">
              <img src="" class="com_img" alt="Image Could not be loaded" width="100%"/>
            </div>
            <p id="p_desc"></p>
            <hr>
            <p>Top Comments</p>
            <div id="ucom"></div>
          </div>
          <div class="modal-footer">
            <div class="customw-80">  
                <form action="" method="POST" id="cform">
                  <div class="form-group myinput">
                    {% csrf_token %}
                    <input type="text" name="comment_desc" class="form-control" oninput="cChange(this)" id="commentp" placeholder="Write a comment...">
                    <button type="submit" class="btn btn-secondary myclass" id="csub" disabled><i class="fa-regular fa-paper-plane"></i></button>
                  </div>
                </form>
            </div>
            <div class="actions">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="DeleteCommentModal" tabindex="-1" role="dialog" data-backdrop="static" backdropClasses='bg-gray-900/50 dark:bg-gray-900/80 fixed inset-0 z-40'>
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content mymodalclass">
          <div class="modal-header text-center">
            <h5 class="modal-title w-100">Delete Comment?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this comment?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-white text-primary" data-dismiss="modal">No</button>
            <a type="submit" href='#' id="delcbtn" class="btn btn-primary">Delete</a>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="PaymentModal" tabindex="-1" role="dialog" aria-labelledby="PaymentModalLongTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-scrollable modal-lg" role="document">
        <div class="modal-content com_modal">
          <div class="modal-header text-center">
            <h5 class="modal-title w-100" id="comptitle">Send stars to support IAS academic</h5>
            <a class="btn btn-warning btn-sm" href="{% url 'products:product-list' %}"><i class="far fa-star"></i> Buy Stars</a>
            <button type="button" class="close" id="cclose" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            
          </div>
          <div class="modal-footer">
            <div class="col-12">  
                <form action="{% url 'post:create_payment' 62 %}" id="sendStars" method="POST">
                  <div class="form-group">
                    {% csrf_token %}
                    <input type="text" name="amount" class="form-control" id="amountp" aria-label="Amount (to the nearest dollar)" required>
                    <input type="hidden" name="received_by" value="" id="stars_received_by">
                    <input type="hidden" name="post" value="" id="stars_sent_on_post">
                    <div class="input-group-append">
                      <span class="input-group-text">$</span>
                      <span class="input-group-text">0.00</span>
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Total Stars:</label>
                    <span class="btn btn-warning" id="quantity_stars">{{ nos }}</span>
                    {% comment %} <input type="hidden" name="hidden_stars" id="hidden_stars" value=""> {% endcomment %}
                  </div>
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary col-12 myclass" id="">Make Payment<i class="fa-regular fa-paper-plane"></i></button>
                  </div>
                  <div class="form-group">
                    {% comment %} <button class="btn btn-light btn-block border border-dark myclass" id="">Cancel Payment<i class="fa-regular fa-paper-plane"></i></button> {% endcomment %}
                    <button type="button" class="btn btn-light btn-block border border-dark myclass" id="cclose" data-dismiss="modal" aria-label="Close">
                      Cancel Payment
                    </button>
                  </div>
                </form>
            </div>
            <div class="">
            </div>
          </div>
        </div>
      </div>
    </div>


    <div style="border: 1px solid blue; width: 10%;background: blue;color: white;font-size: 30px;position: absolute;left: 80%;top: 5%;text-align:center;">
        {{ user.username }}
        <form action="{% url 'user:logout' %}" method="post">                        
            {% csrf_token %}
            <button id="lbtn" type="submit">Log Out</button>
        </form>
    </div>
{% else%}
    <div style="background:red; color: white; text-align: center;"><h1>You are not Logged In !!!</h1></div>
    <a href="{% url 'user:login-page' %}">Login</a>
{% endif %}
{% endblock %}
{% block javas %}
  <script src="{% static 'post/js/script.js' %}"></script>
  <script src="{% static 'user/js/script.js' %}"></script>
{% endblock %}